-- Création des tables dans Oracle (à exécuter avec SQL Developer)

-- Table UTILISATEURS
CREATE TABLE UTILISATEURS (
    ID NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    ROLE VARCHAR2(50),
    STATUT VARCHAR2(20),
    DATE_CREATION DATE DEFAULT SYSDATE
);

-- Création d'une séquence pour auto-incrémentation
CREATE SEQUENCE SEQ_UTILISATEURS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger pour auto-incrémentation
CREATE OR REPLACE TRIGGER TRG_UTILISATEURS
BEFORE INSERT ON UTILISATEURS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_UTILISATEURS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Table MATERIELS
CREATE TABLE MATERIELS (
    ID NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(50),
    QUANTITE NUMBER DEFAULT 0,
    SEUIL_MIN NUMBER DEFAULT 5,
    DATE_AJOUT DATE DEFAULT SYSDATE,
    FOURNISSEUR VARCHAR2(100),
    STATUT VARCHAR2(50)
);

CREATE SEQUENCE SEQ_MATERIELS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_MATERIELS
BEFORE INSERT ON MATERIELS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_MATERIELS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Table CLIENTS
CREATE TABLE CLIENTS (
    ID NUMBER PRIMARY KEY,
    NOM VARCHAR2(50) NOT NULL,
    PRENOM VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    TELEPHONE VARCHAR2(20),
    ADRESSE VARCHAR2(200),
    DATE_INSCRIPTION DATE DEFAULT SYSDATE,
    STATUT VARCHAR2(20)
);

CREATE SEQUENCE SEQ_CLIENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENTS
BEFORE INSERT ON CLIENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_CLIENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Table COMMANDES
CREATE TABLE COMMANDES (
    ID NUMBER PRIMARY KEY,
    CLIENT VARCHAR2(100) NOT NULL,
    TELEPHONE VARCHAR2(20),
    ADRESSE VARCHAR2(200),
    DATE_COMMANDE DATE DEFAULT SYSDATE,
    TYPE_PRODUIT VARCHAR2(50),
    DIMENSIONS NUMBER(10,2),
    MATERIAU VARCHAR2(100),
    QUANTITE NUMBER DEFAULT 1,
    PRIX NUMBER(10,2),
    STATUT VARCHAR2(50)
);

CREATE SEQUENCE SEQ_COMMANDES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_COMMANDES
BEFORE INSERT ON COMMANDES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_COMMANDES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Insertion de quelques données de test
INSERT INTO UTILISATEURS (NOM, EMAIL, ROLE, STATUT, DATE_CREATION)
VALUES ('Admin Principal', 'admin@entreprise.com', 'Admin', 'Actif', TO_DATE('2024-01-15', 'YYYY-MM-DD'));

INSERT INTO UTILISATEURS (NOM, EMAIL, ROLE, STATUT, DATE_CREATION)
VALUES ('Manager RH', 'rh@entreprise.com', 'Responsable', 'Actif', TO_DATE('2024-03-10', 'YYYY-MM-DD'));

INSERT INTO MATERIELS (NOM, TYPE, QUANTITE, SEUIL_MIN, DATE_AJOUT, FOURNISSEUR, STATUT)
VALUES ('Ordinateur portable', 'Informatique', 5, 2, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'Dell', 'Disponible');

INSERT INTO MATERIELS (NOM, TYPE, QUANTITE, SEUIL_MIN, DATE_AJOUT, FOURNISSEUR, STATUT)
VALUES ('Perceuse', 'Outil', 2, 3, TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Bosch', 'Alerte');

COMMIT;