--------------------------------------------------------
--  Fichier créé - mardi-avril-14-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CATEGORIE
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_CATEGORIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTS
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_CLIENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMAND
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_COMMAND"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMANDE
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_COMMANDE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FOURNISSEUR
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_FOURNISSEUR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LIGNE
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_LIGNE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MATERIEL
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_MATERIEL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUIT
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_PRODUIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_UTILISATEUR
--------------------------------------------------------

   CREATE SEQUENCE  "MALEK"."SEQ_UTILISATEUR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AJOUTER
--------------------------------------------------------

  CREATE TABLE "MALEK"."AJOUTER" 
   (	"ID_MATERIEL" NUMBER, 
	"ID_COMMANDE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIE
--------------------------------------------------------

  CREATE TABLE "MALEK"."CATEGORIE" 
   (	"ID_CATEGORIE" NUMBER, 
	"NOM_CATEGORIE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "MALEK"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"DATE_INSCRIPTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "MALEK"."CLIENTS" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(150 BYTE), 
	"DATE_INSCRIPTION" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_UTILISATEUR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMAND
--------------------------------------------------------

  CREATE TABLE "MALEK"."COMMAND" 
   (	"ID_COMMAND" NUMBER(10,0), 
	"ID_CLIENT" NUMBER(10,0), 
	"DATE_COMMANDE" DATE DEFAULT SYSDATE, 
	"STATUT" VARCHAR2(20 BYTE) DEFAULT 'En attente'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "MALEK"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"DATE_COMMANDE" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPOSER
--------------------------------------------------------

  CREATE TABLE "MALEK"."COMPOSER" 
   (	"ID_MATERIEL" NUMBER(10,0), 
	"ID_COMMAND" NUMBER(10,0), 
	"QUANTITE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETAIL_COMMANDE
--------------------------------------------------------

  CREATE TABLE "MALEK"."DETAIL_COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"ID_MATERIEL" NUMBER, 
	"QUANTITE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "MALEK"."FOURNISSEUR" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(150 BYTE), 
	"VILLE" VARCHAR2(50 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"DATE_CREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIGNE_COMMANDE
--------------------------------------------------------

  CREATE TABLE "MALEK"."LIGNE_COMMANDE" 
   (	"ID_LIGNE" NUMBER, 
	"ID_COMMANDE" NUMBER, 
	"ID_PRODUIT" NUMBER, 
	"QUANTITE" NUMBER, 
	"PRIX_UNITAIRE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "MALEK"."MATERIEL" 
   (	"ID_MATERIEL" NUMBER, 
	"NOM_MATERIEL" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"QUANTITE" NUMBER, 
	"SEUIL_MINIMUM" NUMBER, 
	"DATE_AJOUT" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_FOURNISSEUR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PASSER
--------------------------------------------------------

  CREATE TABLE "MALEK"."PASSER" 
   (	"ID_COMMAND" NUMBER(10,0), 
	"ID_CLIENT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "MALEK"."PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"PRIX" NUMBER(10,2), 
	"STOCK" NUMBER, 
	"DATE_AJOUT" DATE, 
	"ID_CATEGORIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUESTIONSDESECURITE
--------------------------------------------------------

  CREATE TABLE "MALEK"."QUESTIONSDESECURITE" 
   (	"MATRICULE" VARCHAR2(50 BYTE), 
	"COLOR" VARCHAR2(50 BYTE), 
	"NOMANIMAL" VARCHAR2(50 BYTE), 
	"ID_UTILISATEUR" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "MALEK"."UTILISATEUR" 
   (	"ID_UTILISATEUR" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"DATE_CREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MALEK.AJOUTER
SET DEFINE OFF;
REM INSERTING into MALEK.CATEGORIE
SET DEFINE OFF;
REM INSERTING into MALEK.CLIENT
SET DEFINE OFF;
REM INSERTING into MALEK.CLIENTS
SET DEFINE OFF;
REM INSERTING into MALEK.COMMAND
SET DEFINE OFF;
REM INSERTING into MALEK.COMMANDE
SET DEFINE OFF;
REM INSERTING into MALEK.COMPOSER
SET DEFINE OFF;
REM INSERTING into MALEK.DETAIL_COMMANDE
SET DEFINE OFF;
REM INSERTING into MALEK.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into MALEK.LIGNE_COMMANDE
SET DEFINE OFF;
REM INSERTING into MALEK.MATERIEL
SET DEFINE OFF;
REM INSERTING into MALEK.PASSER
SET DEFINE OFF;
REM INSERTING into MALEK.PRODUIT
SET DEFINE OFF;
REM INSERTING into MALEK.QUESTIONSDESECURITE
SET DEFINE OFF;
REM INSERTING into MALEK.UTILISATEUR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_DETAIL_COMMANDE
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."PK_DETAIL_COMMANDE" ON "MALEK"."DETAIL_COMMANDE" ("ID_COMMANDE", "ID_MATERIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PASSER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."PK_PASSER" ON "MALEK"."PASSER" ("ID_COMMAND", "ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COMPOSER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."PK_COMPOSER" ON "MALEK"."COMPOSER" ("ID_MATERIEL", "ID_COMMAND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AJOUTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MALEK"."PK_AJOUTER" ON "MALEK"."AJOUTER" ("ID_MATERIEL", "ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_CATEGORIE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_CATEGORIE" 
BEFORE INSERT ON categorie
FOR EACH ROW
BEGIN
    SELECT seq_categorie.NEXTVAL
    INTO :NEW.id_categorie
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_CATEGORIE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CLIENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_CLIENT" 
BEFORE INSERT ON client
FOR EACH ROW
BEGIN
    SELECT seq_client.NEXTVAL
    INTO :NEW.id_client
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_CLIENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CLIENTS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_CLIENTS_ID" 
    BEFORE INSERT ON CLIENTS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENT IS NULL THEN
        SELECT SEQ_CLIENTS.NEXTVAL INTO :NEW.ID_CLIENT FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "MALEK"."TRG_CLIENTS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMMANDE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_COMMANDE" 
BEFORE INSERT ON commande
FOR EACH ROW
BEGIN
    SELECT seq_commande.NEXTVAL
    INTO :NEW.id_commande
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_COMMANDE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_COMMAND_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_COMMAND_ID" 
    BEFORE INSERT ON COMMAND
    FOR EACH ROW
BEGIN
    IF :NEW.ID_COMMAND IS NULL THEN
        SELECT SEQ_COMMAND.NEXTVAL INTO :NEW.ID_COMMAND FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "MALEK"."TRG_COMMAND_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_FOURNISSEUR_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_FOURNISSEUR_ID" 
    BEFORE INSERT ON FOURNISSEUR
    FOR EACH ROW
BEGIN
    IF :NEW.ID_FOURNISSEUR IS NULL THEN
        SELECT SEQ_FOURNISSEUR.NEXTVAL INTO :NEW.ID_FOURNISSEUR FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "MALEK"."TRG_FOURNISSEUR_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LIGNE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_LIGNE" 
BEFORE INSERT ON ligne_commande
FOR EACH ROW
BEGIN
    SELECT seq_ligne.NEXTVAL
    INTO :NEW.id_ligne
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_LIGNE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MATERIEL_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_MATERIEL_ID" 
    BEFORE INSERT ON MATERIEL
    FOR EACH ROW
BEGIN
    IF :NEW.ID_MATERIEL IS NULL THEN
        SELECT SEQ_MATERIEL.NEXTVAL INTO :NEW.ID_MATERIEL FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "MALEK"."TRG_MATERIEL_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUIT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_PRODUIT" 
BEFORE INSERT ON produit
FOR EACH ROW
BEGIN
    SELECT seq_produit.NEXTVAL
    INTO :NEW.id_produit
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_PRODUIT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UTILISATEUR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_UTILISATEUR" 
BEFORE INSERT ON utilisateur
FOR EACH ROW
BEGIN
    SELECT seq_utilisateur.NEXTVAL
    INTO :NEW.id_utilisateur
    FROM dual;
END;

/
ALTER TRIGGER "MALEK"."TRG_UTILISATEUR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_UTILISATEUR_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MALEK"."TRG_UTILISATEUR_ID" 
    BEFORE INSERT ON UTILISATEUR
    FOR EACH ROW
BEGIN
    IF :NEW.ID_UTILISATEUR IS NULL THEN
        SELECT SEQ_UTILISATEUR.NEXTVAL INTO :NEW.ID_UTILISATEUR FROM DUAL;
    END IF;
END;

/
ALTER TRIGGER "MALEK"."TRG_UTILISATEUR_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "MALEK"."PRODUIT" ADD PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."PRODUIT" MODIFY ("NOM_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AJOUTER
--------------------------------------------------------

  ALTER TABLE "MALEK"."AJOUTER" ADD CONSTRAINT "PK_AJOUTER" PRIMARY KEY ("ID_MATERIEL", "ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "MALEK"."FOURNISSEUR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIGNE_COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."LIGNE_COMMANDE" ADD PRIMARY KEY ("ID_LIGNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "MALEK"."CLIENTS" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUESTIONSDESECURITE
--------------------------------------------------------

  ALTER TABLE "MALEK"."QUESTIONSDESECURITE" ADD PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."QUESTIONSDESECURITE" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."QUESTIONSDESECURITE" MODIFY ("NOMANIMAL" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."QUESTIONSDESECURITE" MODIFY ("COLOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETAIL_COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."DETAIL_COMMANDE" ADD CONSTRAINT "PK_DETAIL_COMMANDE" PRIMARY KEY ("ID_COMMANDE", "ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "MALEK"."UTILISATEUR" ADD PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMAND
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMMAND" ADD PRIMARY KEY ("ID_COMMAND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."COMMAND" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPOSER
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMPOSER" ADD CONSTRAINT "PK_COMPOSER" PRIMARY KEY ("ID_MATERIEL", "ID_COMMAND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."COMPOSER" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."COMPOSER" MODIFY ("ID_COMMAND" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."COMPOSER" MODIFY ("ID_MATERIEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "MALEK"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIE
--------------------------------------------------------

  ALTER TABLE "MALEK"."CATEGORIE" ADD PRIMARY KEY ("ID_CATEGORIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."CATEGORIE" MODIFY ("NOM_CATEGORIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMMANDE" ADD PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "MALEK"."MATERIEL" ADD PRIMARY KEY ("ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSER
--------------------------------------------------------

  ALTER TABLE "MALEK"."PASSER" ADD CONSTRAINT "PK_PASSER" PRIMARY KEY ("ID_COMMAND", "ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MALEK"."PASSER" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "MALEK"."PASSER" MODIFY ("ID_COMMAND" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AJOUTER
--------------------------------------------------------

  ALTER TABLE "MALEK"."AJOUTER" ADD CONSTRAINT "FK_AJOUTER_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "MALEK"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "MALEK"."AJOUTER" ADD CONSTRAINT "FK_AJOUTER_MATERIEL" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES "MALEK"."MATERIEL" ("ID_MATERIEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "MALEK"."CLIENTS" ADD CONSTRAINT "FK_CLIENT_USER" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "MALEK"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMAND
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMMAND" ADD CONSTRAINT "FK_COMMAND_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "MALEK"."CLIENTS" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "MALEK"."CLIENTS" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPOSER
--------------------------------------------------------

  ALTER TABLE "MALEK"."COMPOSER" ADD CONSTRAINT "FK_COMPOSER_COMMAND" FOREIGN KEY ("ID_COMMAND")
	  REFERENCES "MALEK"."COMMAND" ("ID_COMMAND") ENABLE;
  ALTER TABLE "MALEK"."COMPOSER" ADD CONSTRAINT "FK_COMPOSER_MATERIEL" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES "MALEK"."MATERIEL" ("ID_MATERIEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETAIL_COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."DETAIL_COMMANDE" ADD CONSTRAINT "FK_DC_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "MALEK"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "MALEK"."DETAIL_COMMANDE" ADD CONSTRAINT "FK_DC_MATERIEL" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES "MALEK"."MATERIEL" ("ID_MATERIEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIGNE_COMMANDE
--------------------------------------------------------

  ALTER TABLE "MALEK"."LIGNE_COMMANDE" ADD CONSTRAINT "FK_LIGNE_COMMANDE" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "MALEK"."COMMANDE" ("ID_COMMANDE") ENABLE;
  ALTER TABLE "MALEK"."LIGNE_COMMANDE" ADD CONSTRAINT "FK_LIGNE_PRODUIT" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "MALEK"."PRODUIT" ("ID_PRODUIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "MALEK"."MATERIEL" ADD CONSTRAINT "FK_MATERIEL_FOURNISSEUR" FOREIGN KEY ("ID_FOURNISSEUR")
	  REFERENCES "MALEK"."FOURNISSEUR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PASSER
--------------------------------------------------------

  ALTER TABLE "MALEK"."PASSER" ADD CONSTRAINT "FK_PASSER_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "MALEK"."CLIENTS" ("ID_CLIENT") ENABLE;
  ALTER TABLE "MALEK"."PASSER" ADD CONSTRAINT "FK_PASSER_COMMAND" FOREIGN KEY ("ID_COMMAND")
	  REFERENCES "MALEK"."COMMAND" ("ID_COMMAND") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "MALEK"."PRODUIT" ADD CONSTRAINT "FK_PRODUIT_CATEGORIE" FOREIGN KEY ("ID_CATEGORIE")
	  REFERENCES "MALEK"."CATEGORIE" ("ID_CATEGORIE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTIONSDESECURITE
--------------------------------------------------------

  ALTER TABLE "MALEK"."QUESTIONSDESECURITE" ADD CONSTRAINT "FK_QUESTIONS_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "MALEK"."UTILISATEUR" ("ID_UTILISATEUR") ON DELETE CASCADE ENABLE;
